name: default

ffmpeg:
  version: 7.1
  enable_ffplay: false
  gpl: true
  nonfree: false         # no fdk-aac, fully redistributable GPL build
  ld_static: true

codecs:
  x264:   true
  x265:   true
  aom:    true           # libaom AV1
  svtav1: false          # enable if you want speedier AV1
  vpx:    true           # VP8/VP9
  opus:   true
  fdk_aac: false
  ass:    true           # libass stack (freetype/fribidi/harfbuzz/libass)
  vmaf:   true
  srt:    true

system:
  parallel: 8

ports:
  x264:
    version: "stable"    # handled in x264.sh (e.g. latest master or tag)
  x265:
    version: "3.6"
  aom:
    version: "v3.9.0"
  svtav1:
    version: "v2.2.1"
  vpx:
    version: "v1.14.1"
  opus:
    version: "v1.5.1"
  openssl:
    version: "3.3.2"
  srt:
    version: "v1.5.4"
  vmaf:
    version: "v3.0.0"
  libass:
    version: "0.17.3"
